In [1]:
#import lib
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.svm import SVC

In [2]:
df=pd.read_csv('Crop_recommendation.csv')

In [3]:
df

N   P   K  temperature   humidity        ph    rainfall   label
0      90  42  43    20.879744  82.002744  6.502985  202.935536    rice
1      85  58  41    21.770462  80.319644  7.038096  226.655537    rice
2      60  55  44    23.004459  82.320763  7.840207  263.964248    rice
3      74  35  40    26.491096  80.158363  6.980401  242.864034    rice
4      78  42  42    20.130175  81.604873  7.628473  262.717340    rice
...   ...  ..  ..          ...        ...       ...         ...     ...
2195  107  34  32    26.774637  66.413269  6.780064  177.774507  coffee
2196   99  15  27    27.417112  56.636362  6.086922  127.924610  coffee
2197  118  33  30    24.131797  67.225123  6.362608  173.322839  coffee
2198  117  32  34    26.272418  52.127394  6.758793  127.175293  coffee
2199  104  18  30    23.603016  60.396475  6.779833  140.937041  coffee

[2200 rows x 8 columns]

In [4]:
df.shape

(2200, 8)

In [5]:
df.isnull().sum()

N              0
P              0
K              0
temperature    0
humidity       0
ph             0
rainfall       0
label          0
dtype: int64

In [6]:
X=df.drop( ['temperature','humidity','rainfall','label'],axis=1)

In [7]:
y=df['label']

In [8]:
X

N   P   K        ph
0      90  42  43  6.502985
1      85  58  41  7.038096
2      60  55  44  7.840207
3      74  35  40  6.980401
4      78  42  42  7.628473
...   ...  ..  ..       ...
2195  107  34  32  6.780064
2196   99  15  27  6.086922
2197  118  33  30  6.362608
2198  117  32  34  6.758793
2199  104  18  30  6.779833

[2200 rows x 4 columns]

In [9]:
y

0         rice
1         rice
2         rice
3         rice
4         rice
         ...  
2195    coffee
2196    coffee
2197    coffee
2198    coffee
2199    coffee
Name: label, Length: 2200, dtype: object

In [10]:
xdf = df.copy()
xdf

N   P   K  temperature   humidity        ph    rainfall   label
0      90  42  43    20.879744  82.002744  6.502985  202.935536    rice
1      85  58  41    21.770462  80.319644  7.038096  226.655537    rice
2      60  55  44    23.004459  82.320763  7.840207  263.964248    rice
3      74  35  40    26.491096  80.158363  6.980401  242.864034    rice
4      78  42  42    20.130175  81.604873  7.628473  262.717340    rice
...   ...  ..  ..          ...        ...       ...         ...     ...
2195  107  34  32    26.774637  66.413269  6.780064  177.774507  coffee
2196   99  15  27    27.417112  56.636362  6.086922  127.924610  coffee
2197  118  33  30    24.131797  67.225123  6.362608  173.322839  coffee
2198  117  32  34    26.272418  52.127394  6.758793  127.175293  coffee
2199  104  18  30    23.603016  60.396475  6.779833  140.937041  coffee

[2200 rows x 8 columns]

In [11]:
from sklearn.preprocessing import LabelEncoder 
labelencoder= LabelEncoder() 

In [12]:
xdf['label_codes'] = labelencoder.fit_transform(xdf['label']) 
xdf

N   P   K  temperature   humidity        ph    rainfall   label  \
0      90  42  43    20.879744  82.002744  6.502985  202.935536    rice   
1      85  58  41    21.770462  80.319644  7.038096  226.655537    rice   
2      60  55  44    23.004459  82.320763  7.840207  263.964248    rice   
3      74  35  40    26.491096  80.158363  6.980401  242.864034    rice   
4      78  42  42    20.130175  81.604873  7.628473  262.717340    rice   
...   ...  ..  ..          ...        ...       ...         ...     ...   
2195  107  34  32    26.774637  66.413269  6.780064  177.774507  coffee   
2196   99  15  27    27.417112  56.636362  6.086922  127.924610  coffee   
2197  118  33  30    24.131797  67.225123  6.362608  173.322839  coffee   
2198  117  32  34    26.272418  52.127394  6.758793  127.175293  coffee   
2199  104  18  30    23.603016  60.396475  6.779833  140.937041  coffee   

      label_codes  
0              20  
1              20  
2              20  
3              20  
4              20  
...           ...  
2195            5  
2196            5  
2197            5  
2198            5  
2199            5  

[2200 rows x 9 columns]

In [13]:
X = xdf.drop(['temperature','humidity','rainfall','label','label_codes'],axis = 1)

In [14]:
y = xdf['label_codes']

In [15]:
X

N   P   K        ph
0      90  42  43  6.502985
1      85  58  41  7.038096
2      60  55  44  7.840207
3      74  35  40  6.980401
4      78  42  42  7.628473
...   ...  ..  ..       ...
2195  107  34  32  6.780064
2196   99  15  27  6.086922
2197  118  33  30  6.362608
2198  117  32  34  6.758793
2199  104  18  30  6.779833

[2200 rows x 4 columns]

In [16]:
y

0       20
1       20
2       20
3       20
4       20
        ..
2195     5
2196     5
2197     5
2198     5
2199     5
Name: label_codes, Length: 2200, dtype: int32

In [17]:
y.unique()

array([20, 11,  3,  9, 18, 13, 14,  2, 10, 19,  1, 12,  7, 21, 15,  0, 16,
       17,  4,  6,  8,  5])

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, test_size=0.3)

In [20]:
from sklearn.linear_model import LinearRegression

In [21]:
reg=LinearRegression()

In [22]:
reg.fit(Xtrain, ytrain)

LinearRegression()

In [23]:
ytest

1407    15
1839     4
775      2
647     14
2083     8
        ..
2128     5
2024     8
1498    15
1802     4
891     10
Name: label_codes, Length: 660, dtype: int32

In [24]:
pred=reg.predict(Xtest)

In [25]:
pred

array([12.00160571, 15.21643541,  9.66662952, 11.17069142, 10.21103699,
        9.14179216,  6.99558886, 12.94788487,  9.91217368, 10.95043639,
        9.49577392,  9.9691531 ,  7.60376974, 15.1933902 ,  9.32678994,
       11.07631483,  7.85156875, 16.81233671, 12.38962838,  7.67913806,
       14.25463692,  8.1752103 , 12.98097455, 10.42106159, 10.10089708,
       14.01182555,  9.21795028, 14.09822444,  6.43878663, 12.22091297,
        7.89281629, 13.5268697 , 11.68102718,  9.37274427,  9.57904473,
       15.78232594,  8.78431911, 13.36445562, 13.33329933, 16.63796641,
       11.34089932,  8.81698531, 15.00020392,  8.27212844, 13.18866435,
        9.91995829,  9.18276326, 12.78530265,  8.97875208,  8.92538815,
       14.99487646, 10.86131247, 11.00411122, 11.32089304, 13.41443916,
       13.75181049,  9.99841534,  4.28441149,  8.07813248, 13.77935182,
       15.54166636, 15.70165448, 10.79006079,  4.66545492,  9.05603149,
       14.10694432,  9.91062308, 14.26966743, 10.0307102 , 11.97

In [26]:
from sklearn.metrics import mean_squared_error

In [27]:
accuracy_train = []
accuracy_test = []
model_name = []

In [28]:
predict_linear_train = reg.predict(Xtrain)
MSE_linear_train = ( mean_squared_error(ytrain, predict_linear_train)  )

accuracy_linear_train = 100 - MSE_linear_train
print("Train Accuracy: ", accuracy_linear_train)

Train Accuracy:  70.07480314689772


In [29]:
predict_linear_test = reg.predict(Xtest)
MSE_linear_test = ( mean_squared_error(ytest, predict_linear_test)  )
accuracy_linear_test = 100 - MSE_linear_test
print("Test Accuracy: ", accuracy_linear_test)

accuracy_train.append( accuracy_linear_train )
accuracy_test.append( accuracy_linear_test )
model_name.append('Linear Regression')

Test Accuracy:  71.56950137847538


In [30]:
dftable = pd.DataFrame(columns={'accuracy_train', 'accuracy_test', 'model_name'})
dftable['accuracy_train'] = accuracy_train
dftable['accuracy_test'] = accuracy_test
dftable['model_name'] = model_name
dftable = dftable[['model_name', 'accuracy_train', 'accuracy_test']]
dftable

model_name  accuracy_train  accuracy_test
0  Linear Regression       70.074803      71.569501

In [31]:
from joblib import dump

In [32]:
dump(reg, './../Model/reg.joblib')

['./../Model/reg.joblib']

In [33]:
import pickle

In [34]:
pickle.dump(reg, open("Linear_Reg.sav", "wb"))


In [35]:
with open('model_pickle','wb') as file:
    pickle.dump(reg,file)

In [36]:
with open('model_pickle','rb') as file:
    mp = pickle.load(file)

In [37]:
mp.coef_

array([-0.02330464, -0.11070812,  0.00526163, -0.53673343])

In [38]:
mp.intercept_

20.96876208700749

In [39]:
pd.to_pickle(reg,r'C:\Users\User\Desktop\299\CSE-299-Project\Model\modelpickle')

In [40]:
model = pd.read_pickle(r'C:\Users\User\Desktop\299\CSE-299-Project\Model\modelpickle') 

In [41]:
N = float(input("N: "))
P = float(input("P: "))
K = float(input("K: "))
ph = float(input("ph: "))

result = model.predict([[N ,P, K, ph]])
print(result)

N: 5
P: 5
K: 5
ph: 6
[17.1046059]


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


model = SVC(gamma='auto')
model.fit(Xtrain, ytrain)


predictions = model.predict(Xtest)




In [44]:
pickle.dump(reg, open("Linear_Reg.pkl", "wb"))

In [45]:
new = pickle.load(open("Linear_Reg.pkl", "rb"))

In [46]:
model.predict([[5,6,7,8]])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([15.93095419])