In [5]:
#import lib
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [6]:
df=pd.read_csv('Crop_recommendation.csv')

In [7]:
df

N   P   K  temperature   humidity        ph    rainfall   label
0      90  42  43    20.879744  82.002744  6.502985  202.935536    rice
1      85  58  41    21.770462  80.319644  7.038096  226.655537    rice
2      60  55  44    23.004459  82.320763  7.840207  263.964248    rice
3      74  35  40    26.491096  80.158363  6.980401  242.864034    rice
4      78  42  42    20.130175  81.604873  7.628473  262.717340    rice
...   ...  ..  ..          ...        ...       ...         ...     ...
2195  107  34  32    26.774637  66.413269  6.780064  177.774507  coffee
2196   99  15  27    27.417112  56.636362  6.086922  127.924610  coffee
2197  118  33  30    24.131797  67.225123  6.362608  173.322839  coffee
2198  117  32  34    26.272418  52.127394  6.758793  127.175293  coffee
2199  104  18  30    23.603016  60.396475  6.779833  140.937041  coffee

[2200 rows x 8 columns]

In [8]:
df.shape

(2200, 8)

In [9]:
df.isnull().sum()

N              0
P              0
K              0
temperature    0
humidity       0
ph             0
rainfall       0
label          0
dtype: int64

In [64]:
X=df.drop(['humidity','rainfall','label'],axis=1)

In [65]:
y=df['label']

In [66]:
X

N   P   K  temperature        ph
0      90  42  43    20.879744  6.502985
1      85  58  41    21.770462  7.038096
2      60  55  44    23.004459  7.840207
3      74  35  40    26.491096  6.980401
4      78  42  42    20.130175  7.628473
...   ...  ..  ..          ...       ...
2195  107  34  32    26.774637  6.780064
2196   99  15  27    27.417112  6.086922
2197  118  33  30    24.131797  6.362608
2198  117  32  34    26.272418  6.758793
2199  104  18  30    23.603016  6.779833

[2200 rows x 5 columns]

In [67]:
y

0         rice
1         rice
2         rice
3         rice
4         rice
         ...  
2195    coffee
2196    coffee
2197    coffee
2198    coffee
2199    coffee
Name: label, Length: 2200, dtype: object

In [68]:
xdf = df.copy()

In [69]:
xdf

N   P   K  temperature   humidity        ph    rainfall   label
0      90  42  43    20.879744  82.002744  6.502985  202.935536    rice
1      85  58  41    21.770462  80.319644  7.038096  226.655537    rice
2      60  55  44    23.004459  82.320763  7.840207  263.964248    rice
3      74  35  40    26.491096  80.158363  6.980401  242.864034    rice
4      78  42  42    20.130175  81.604873  7.628473  262.717340    rice
...   ...  ..  ..          ...        ...       ...         ...     ...
2195  107  34  32    26.774637  66.413269  6.780064  177.774507  coffee
2196   99  15  27    27.417112  56.636362  6.086922  127.924610  coffee
2197  118  33  30    24.131797  67.225123  6.362608  173.322839  coffee
2198  117  32  34    26.272418  52.127394  6.758793  127.175293  coffee
2199  104  18  30    23.603016  60.396475  6.779833  140.937041  coffee

[2200 rows x 8 columns]

In [70]:
from sklearn.preprocessing import LabelEncoder 

In [71]:
labelencoder= LabelEncoder() 

In [72]:
xdf['label_codes'] = labelencoder.fit_transform(xdf['label'])

In [73]:
xdf

N   P   K  temperature   humidity        ph    rainfall   label  \
0      90  42  43    20.879744  82.002744  6.502985  202.935536    rice   
1      85  58  41    21.770462  80.319644  7.038096  226.655537    rice   
2      60  55  44    23.004459  82.320763  7.840207  263.964248    rice   
3      74  35  40    26.491096  80.158363  6.980401  242.864034    rice   
4      78  42  42    20.130175  81.604873  7.628473  262.717340    rice   
...   ...  ..  ..          ...        ...       ...         ...     ...   
2195  107  34  32    26.774637  66.413269  6.780064  177.774507  coffee   
2196   99  15  27    27.417112  56.636362  6.086922  127.924610  coffee   
2197  118  33  30    24.131797  67.225123  6.362608  173.322839  coffee   
2198  117  32  34    26.272418  52.127394  6.758793  127.175293  coffee   
2199  104  18  30    23.603016  60.396475  6.779833  140.937041  coffee   

      label_codes  
0              20  
1              20  
2              20  
3              20  
4              20  
...           ...  
2195            5  
2196            5  
2197            5  
2198            5  
2199            5  

[2200 rows x 9 columns]

In [75]:
X = xdf.drop(['humidity','rainfall','label','label_codes'],axis = 1)

In [76]:
y = xdf['label_codes']

In [77]:
X

N   P   K  temperature        ph
0      90  42  43    20.879744  6.502985
1      85  58  41    21.770462  7.038096
2      60  55  44    23.004459  7.840207
3      74  35  40    26.491096  6.980401
4      78  42  42    20.130175  7.628473
...   ...  ..  ..          ...       ...
2195  107  34  32    26.774637  6.780064
2196   99  15  27    27.417112  6.086922
2197  118  33  30    24.131797  6.362608
2198  117  32  34    26.272418  6.758793
2199  104  18  30    23.603016  6.779833

[2200 rows x 5 columns]

In [78]:
y

0       20
1       20
2       20
3       20
4       20
        ..
2195     5
2196     5
2197     5
2198     5
2199     5
Name: label_codes, Length: 2200, dtype: int32

In [79]:
y.unique()

array([20, 11,  3,  9, 18, 13, 14,  2, 10, 19,  1, 12,  7, 21, 15,  0, 16,
       17,  4,  6,  8,  5])

In [80]:
from sklearn.model_selection import train_test_split

In [81]:
Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, test_size=0.3)

In [82]:
from sklearn.linear_model import LinearRegression

In [83]:
reg=LinearRegression()

In [84]:
reg.fit(Xtrain, ytrain)

LinearRegression()

In [85]:
ytest

439     18
794      2
1314    21
2117     5
559     13
        ..
668     14
943     19
1653    16
685     14
305      9
Name: label_codes, Length: 660, dtype: int32

In [86]:
pred=reg.predict(Xtest)

In [87]:
pred

array([11.40698062,  9.0590946 , 13.22301244, 12.05368841,  9.17691476,
        3.08287823,  9.07144796,  9.34243553,  9.74827496, 10.75515012,
        3.70679475, 13.26540938,  9.69642644, 10.37635183, 10.06764328,
       13.68325537,  3.65387962, 13.26547101, 15.63133592, 15.45039554,
       11.03335915,  9.24941807,  8.63791661,  9.62049458,  1.46192477,
        8.87608654, 13.86295506,  9.31802394,  1.83906026,  1.61552367,
       10.37803258, 11.53883713,  9.50568339,  9.7169844 ,  2.84667793,
       10.14283778,  9.94884211, 12.44292236,  2.82685016,  7.71044827,
        4.86520326, 11.98548498, 11.49565203,  9.83266219, 11.14654599,
        7.88296849,  9.57017807, 14.53215069,  9.86822759,  8.44770172,
       10.26313033,  3.27596931, 11.39659115, 10.29568297,  8.49287252,
        9.64565404, 12.83113391,  3.48775964, 10.79505248,  8.55626358,
       11.67699444,  4.48728448, 12.54123804, 11.28861103, 12.70144126,
       10.25360229, 16.73466273,  2.89029763, 13.98647125,  8.72

In [88]:
from sklearn.metrics import mean_squared_error

In [89]:
accuracy_train = []
accuracy_test = []
model_name = []

In [90]:
predict_linear_train = reg.predict(Xtrain)
MSE_linear_train = ( mean_squared_error(ytrain, predict_linear_train)  )

accuracy_linear_train = 100 - MSE_linear_train
print("Train Accuracy: ", accuracy_linear_train)

Train Accuracy:  69.97381217747105


In [91]:
predict_linear_test = reg.predict(Xtest)
MSE_linear_test = ( mean_squared_error(ytest, predict_linear_test)  )
accuracy_linear_test = 100 - MSE_linear_test
print("Test Accuracy: ", accuracy_linear_test)

accuracy_train.append( accuracy_linear_train )
accuracy_test.append( accuracy_linear_test )
model_name.append('Linear Regression')

Test Accuracy:  72.24443556799261


In [92]:
from sklearn.tree import DecisionTreeClassifier

In [93]:
from sklearn.pipeline import make_pipeline

In [94]:
dt_pipeline = make_pipeline(DecisionTreeClassifier(criterion="entropy", random_state=2, max_depth=5))

In [95]:
dt_pipeline.fit(Xtrain,ytrain)

Pipeline(steps=[('decisiontreeclassifier',
                 DecisionTreeClassifier(criterion='entropy', max_depth=5,
                                        random_state=2))])

In [96]:
from sklearn.metrics import accuracy_score

In [97]:
decision_pred_train = dt_pipeline.predict(Xtrain)
decision_accuracy_train = accuracy_score(ytrain, decision_pred_train)
print(f"Train Accuracy: {decision_accuracy_train * 100:2f}%")

Train Accuracy: 80.519481%


In [98]:
decision_pred_test = dt_pipeline.predict(Xtest)
decision_accuracy_test = accuracy_score(ytest, decision_pred_test)
print(f"Test Accuracy: {decision_accuracy_test * 100:2f}%")

Test Accuracy: 76.515152%


In [99]:
import pickle

In [100]:
pickle.dump(reg, open("final.sav", "wb"))

In [101]:
with open('newp','wb') as file:
    pickle.dump(reg,file)

In [102]:
with open('newp','rb') as file:
    mp = pickle.load(file)

In [103]:
mp.coef_

array([-0.02360221, -0.10633645,  0.00413049,  0.06057293, -0.6595074 ])

In [106]:
mp.intercept_

19.820199864374803

In [107]:
pd.to_pickle(reg,r'C:\Users\User\Desktop\ML\newp')

In [108]:
model = pd.read_pickle(r'C:\Users\User\Desktop\ML\newp')

In [110]:
N = int(input("N: "))
P = int(input("P: "))
K = int(input("K: "))
ph = int(input("ph: "))
temparature = int(input("ph: "))

result = int(model.predict([[N ,P, K, ph, humidity]]))
print(result)

N: 5
P: 6
K: 5
ph: 9
ph: 20
-29


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [111]:
pickle.dump(reg, open("newPrediction.pkl", "wb"))

In [112]:
new = pickle.load(open("newPrediction.pkl", "rb"))

In [126]:
new.predict([[7,73,25,7,28]])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([-6.04651068])